const recipes = [
  {
    title: "Vegane Spaghetti Carbonara",
    type: "Vegan",
    ingredients: [
      { name: "Spaghetti", amount: "200", unit: "g" },
      { name: "Cashewkerne (eingeweicht)", amount: "100", unit: "g" },
      { name: "Hefeflocken", amount: "2", unit: "EL" },
      { name: "Zitronensaft", amount: "1", unit: "TL" },
      { name: "Knoblauchzehe", amount: "1" },
      { name: "Olivenöl", amount: "1", unit: "EL" },
      { name: "Salz", amount: "nach Geschmack" },
      { name: "Pfeffer", amount: "nach Geschmack" },
    ],
    images: ["../../assets/frite-salad.png"],

    cookingTime: "25 Minuten",
  },
  {
    title: "Vegane Tomaten-Basilikum-Pasta",
    type: "Vegan",
    ingredients: [
      { name: "Pasta (z. B. Penne)", amount: "250", unit: "g" },
      { name: "Tomaten", amount: "4-5 Stück, gewürfelt" },
      { name: "Frühlingszwiebeln", amount: "2 Stück, in Scheiben geschnitten" },
      { name: "Knoblauchzehe", amount: "1" },
      { name: "Olivenöl", amount: "2", unit: "EL" },
      { name: "frisches Basilikum", amount: "eine Handvoll, gehackt" },
      { name: "Salz", amount: "nach Geschmack" },
      { name: "Pfeffer", amount: "nach Geschmack" },
    ],
    images: ["", ""],
    cookingTime: "20 Minuten",
  },
  {
    title: "Vegane Pesto-Spaghetti",
    type: "Vegan",
    ingredients: [
      { name: "Spaghetti", amount: "200", unit: "g" },
      { name: "Veganes Pesto", amount: "4", unit: "EL" },
      { name: "Cherrytomaten", amount: "halbiert, 10 Stück" },
      { name: "Pinienkerne", amount: "2", unit: "EL, geröstet" },
      { name: "Frisches Basilikum", amount: "einige Blätter zum Garnieren" },
      { name: "Olivenöl", amount: "2", unit: "EL" },
      { name: "Salz", amount: "nach Geschmack" },
      { name: "Pfeffer", amount: "nach Geschmack" },
    ],
    images: ["", ""],
    cookingTime: "15 Minuten",
  },
  //-------------Burger--------
  {
    title: "Klassischer Cheeseburger",
    type: "Burger",
    ingredients: [
      { name: "Rindfleisch-Patties", amount: "2", unit: "Stück (je 150 g)" },
      { name: "Cheddar-Käse (Scheiben)", amount: "4", unit: "Scheiben" },
      { name: "Burgerbrötchen", amount: "2", unit: "Stück" },
      { name: "Tomatenscheiben", amount: "nach Bedarf" },
      { name: "Salatblätter", amount: "nach Bedarf" },
      { name: "Zwiebelringe", amount: "nach Bedarf" },
      { name: "Essiggurken", amount: "nach Bedarf" },
      { name: "Ketchup", amount: "nach Bedarf" },
      { name: "Senf", amount: "nach Bedarf" },
    ],
    images: ["", ""],
    cookingTime: "20 Minuten",
  },
  {
    title: "Veggie-Quinoa-Burger",
    type: "Burger",
    ingredients: [
      { name: "Quinoa", amount: "100", unit: "g" },
      { name: "Karotten", amount: "2", unit: "Stück (gerieben)" },
      { name: "Zucchini", amount: "1", unit: "Stück (gerieben)" },
      { name: "Haferflocken", amount: "50", unit: "g" },
      { name: "Knoblauchzehe", amount: "1", unit: "Stück" },
      { name: "Zwiebel", amount: "1", unit: "Stück (gehackt)" },
      { name: "Kichererbsen", amount: "200", unit: "g (gekocht)" },
      { name: "Kreuzkümmel", amount: "1", unit: "TL" },
      { name: "Paprikapulver", amount: "1", unit: "TL" },
      { name: "Salz", amount: "nach Geschmack" },
      { name: "Pfeffer", amount: "nach Geschmack" },
      { name: "Olivenöl", amount: "2", unit: "EL" },
      { name: "Burgerbrötchen", amount: "2", unit: "Stück" },
      { name: "Salatblätter", amount: "nach Bedarf" },
      { name: "Tomatenscheiben", amount: "nach Bedarf" },
      { name: "Vegane Mayonnaise", amount: "2", unit: "EL" },
    ],
    images: ["", ""],
    cookingTime: "30 Minuten",
  },
  {
    title: "Mediterraner Halloumi-Burger",
    type: "Burger",
    ingredients: [
      {
        name: "Halloumi-Käse",
        amount: "200",
        unit: "g (in Scheiben geschnitten)",
      },
      { name: "Burgerbrötchen", amount: "2", unit: "Stück" },
      { name: "Rucola", amount: "eine Handvoll" },
      { name: "Getrocknete Tomaten", amount: "4-5", unit: "Stück" },
      { name: "Pesto", amount: "2", unit: "EL" },
      { name: "Olivenöl", amount: "1", unit: "EL" },
      { name: "Balsamico-Glace", amount: "1", unit: "EL" },
      { name: "Salz", amount: "nach Geschmack" },
      { name: "Pfeffer", amount: "nach Geschmack" },
    ],
    images: ["", ""],
    cookingTime: "25 Minuten",
  },
  {
    title: "BBQ-Black-Bean-Burger",
    type: "Burger",
    ingredients: [
      {
        name: "Schwarze Bohnen",
        amount: "400",
        unit: "g (gekocht und abgetropft)",
      },
      { name: "Haferflocken", amount: "100", unit: "g" },
      { name: "Zwiebel", amount: "1", unit: "Stück (gehackt)" },
      { name: "Knoblauchzehe", amount: "2", unit: "Stück" },
      { name: "Paniermehl", amount: "3", unit: "EL" },
      { name: "BBQ-Sauce", amount: "3", unit: "EL" },
      { name: "Paprikapulver", amount: "1", unit: "TL" },
      { name: "Kreuzkümmel", amount: "1", unit: "TL" },
      { name: "Salz", amount: "nach Geschmack" },
      { name: "Pfeffer", amount: "nach Geschmack" },
      { name: "Burgerbrötchen", amount: "2", unit: "Stück" },
      { name: "Salatblätter", amount: "nach Bedarf" },
      { name: "Tomatenscheiben", amount: "nach Bedarf" },
      { name: "Rote Zwiebelringe", amount: "nach Bedarf" },
    ],
    images: ["", ""],
    cookingTime: "25 Minuten",
  },
  //--------Asiatisch----------
  {
    title: "Pad Thai",
    type: "Asiatisch",
    ingredients: [
      { name: "Reisnudeln", amount: "200", unit: "g" },
      { name: "Tofu", amount: "150", unit: "g (gewürfelt)" },
      { name: "Eier", amount: "2", unit: "Stück" },
      { name: "Knoblauch", amount: "2", unit: "Knoblauchzehen (gehackt)" },
      {
        name: "Frühlingszwiebeln",
        amount: "3",
        unit: "Stück (in Ringe geschnitten)",
      },
      { name: "Sojasoße", amount: "3", unit: "EL" },
      { name: "Tamarindenpaste", amount: "2", unit: "EL" },
      { name: "Limettensaft", amount: "1", unit: "EL" },
      { name: "Erdnüsse", amount: "3", unit: "EL (gehackt)" },
      { name: "Bohnenkeimlinge", amount: "50", unit: "g" },
      { name: "Öl", amount: "2", unit: "EL" },
    ],
    images: ["", ""],
    cookingTime: "25 Minuten",
  },
  {
    title: "Sushi-Rollen",
    type: "Asiatisch",
    ingredients: [
      { name: "Sushi-Reis", amount: "200", unit: "g" },
      { name: "Nori-Algenblätter", amount: "5", unit: "Stück" },
      { name: "Avocado", amount: "1", unit: "Stück (in Streifen geschnitten)" },
      { name: "Gurke", amount: "1", unit: "Stück (in Streifen geschnitten)" },
      {
        name: "Karotten",
        amount: "1",
        unit: "Stück (in Streifen geschnitten)",
      },
      {
        name: "Räucher-Tofu",
        amount: "100",
        unit: "g (in Streifen geschnitten)",
      },
      { name: "Sojasoße", amount: "zum Dippen" },
      { name: "Ingwer", amount: "zum Dippen" },
      { name: "Wasabi", amount: "zum Dippen" },
      { name: "Sushi-Matte", amount: "1", unit: "Stück" },
    ],
    images: ["", ""],
    cookingTime: "30 Minuten",
  },
  {
    title: "Gebratener Reis mit Gemüse",
    type: "Asiatisch",
    ingredients: [
      { name: "Reis", amount: "200", unit: "g (gekocht und abgekühlt)" },
      {
        name: "Gemüse (Brokkoli, Karotten, Paprika, Erbsen, etc.)",
        amount: "200",
        unit: "g",
      },
      { name: "Knoblauch", amount: "2", unit: "Knoblauchzehen (gehackt)" },
      { name: "Ingwer", amount: "1", unit: "EL (gerieben)" },
      { name: "Sojasoße", amount: "3", unit: "EL" },
      { name: "Sesamöl", amount: "2", unit: "EL" },
      { name: "Ei", amount: "2", unit: "Stück" },
      {
        name: "Frühlingszwiebeln",
        amount: "3",
        unit: "Stück (in Ringe geschnitten)",
      },
      { name: "Salz", amount: "nach Geschmack" },
      { name: "Pfeffer", amount: "nach Geschmack" },
    ],
    images: ["", ""],
    cookingTime: "20 Minuten",
  },

  //---Sonstige-----
  {
    title: "Sommerlicher Wassermelonen-Feta-Salat",
    type: "Sonstige",
    ingredients: [
      {
        name: "Wassermelone",
        amount: "500",
        unit: "g (in Würfel geschnitten)",
      },
      {
        name: "Feta-Käse",
        amount: "150",
        unit: "g (in kleine Stücke gebrochen)",
      },
      {
        name: "Rote Zwiebel",
        amount: "1/2",
        unit: "Stück (in dünne Scheiben geschnitten)",
      },
      { name: "Frische Minze", amount: "eine", unit: "Handvoll (gehackt)" },
      { name: "Olivenöl", amount: "2", unit: "EL" },
      { name: "Balsamico-Essig", amount: "1", unit: "EL" },
      { name: "Salz", amount: "nach Geschmack" },
      { name: "Pfeffer", amount: "nach Geschmack" },
      { name: "Walnüsse", amount: "eine", unit: "Handvoll (gehackt)" },
    ],
    images: ["", ""],
    cookingTime: "15 Minuten",
  },
  {
    title: "Vegetarische Paella",
    type: "Sonstige",
    ingredients: [
      { name: "Rundkornreis", amount: "200", unit: "g" },
      { name: "Zwiebel", amount: "1", unit: "Stück (gehackt)" },
      { name: "Knoblauch", amount: "2", unit: "Knoblauchzehen (gehackt)" },
      { name: "Paprika", amount: "1", unit: "Stück (in Streifen geschnitten)" },
      { name: "Tomaten", amount: "2", unit: "Stück (gewürfelt)" },
      { name: "Artischockenherzen", amount: "200", unit: "g (halbiert)" },
      {
        name: "Gewürze (Paprikapulver, Safran, etc.)",
        amount: "nach Geschmack",
      },
      { name: "Gemüsebrühe", amount: "500", unit: "ml" },
      { name: "Erbsen", amount: "100", unit: "g" },
      { name: "Olivenöl", amount: "2", unit: "EL" },
      { name: "Zitrone", amount: "1", unit: "Stück (in Scheiben geschnitten)" },
    ],
    images: ["", ""],
    cookingTime: "40 Minuten",
  },
  {
    title: "Griechischer Bauernsalat",
    type: "Sonstige",
    ingredients: [
      { name: "Gurke", amount: "1", unit: "Stück (gewürfelt)" },
      { name: "Tomaten", amount: "2", unit: "Stück (gewürfelt)" },
      {
        name: "Rote Zwiebel",
        amount: "1/2",
        unit: "Stück (in dünne Scheiben geschnitten)",
      },
      { name: "Oliven", amount: "eine", unit: "Handvoll" },
      { name: "Feta-Käse", amount: "150", unit: "g (in Würfel geschnitten)" },
      {
        name: "Grüne Paprika",
        amount: "1",
        unit: "Stück (in Streifen geschnitten)",
      },
      {
        name: "Frische Petersilie",
        amount: "eine",
        unit: "Handvoll (gehackt)",
      },
      { name: "Olivenöl", amount: "2", unit: "EL" },
      { name: "Balsamico-Essig", amount: "1", unit: "EL" },
      { name: "Salz", amount: "nach Geschmack" },
      { name: "Pfeffer", amount: "nach Geschmack" },
    ],
    images: ["", ""],
    cookingTime: "20 Minuten",
  },
];

export default recipes;
